; to use the default value for a field, simply comment it out or remove it

[colors]

; git
git_dirty = #AF5F00
git_clean = #00AF5F

; other
current_dir = #5F5F63
prompt = #8C8F92

[icons]

git_dirty = •
git_clean = •
prompt = ✽

[settings]

; add newline before prompt (yes | no)
newline = yes
