
; To use the default value(s) for a field or section:
; simply comment it out or remove it

[colors]

; git
git_dirty = #AF5F00
git_clean = #00AF5F

; other
current_dir = #5F5F63
prompt = #8C8F92

[icons]

git_dirty = •
git_clean = •
prompt = ✽
